name: 编译 Structura
run-name: Build Structura
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Build:
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4.1.1
      - name: Bundle application
        run: |
          pip install -r requirements.txt -U pyinstaller
          pyinstaller --clean --onefile structura.py
          move LICENSE dist/LICENSE
          tree /f
      - name: 上传附件
        uses: actions/upload-artifact@v4
        with:
          name: Structura
          path: dist